channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - pip
  - pyqt  # conda-forge's pyqt works better on Travis than pip's PyQt5
  - python=3
  - pip:
    - elephant>=0.6.2
    - ephyviewer>=1.1.0
    - neo>=0.7.2
    - numpy
    - packaging
    - pandas
    - pylttb
    - pyyaml
    - quantities
    - tqdm
